# Generated by Django 4.0.4 on 2022-05-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id_guest', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('patronimyc', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id_room_type', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=50)),
                ('beds', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id_room', models.IntegerField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('room_floor', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('id_room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafelab.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.IntegerField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField()),
                ('checkin_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField()),
                ('guest_number', models.IntegerField()),
                ('number_of_nights', models.IntegerField()),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafelab.guest')),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafelab.room')),
            ],
        ),
    ]
